# Generated by Django 5.0.3 on 2024-03-31 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_telegramuserincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Сообщение пользователя.', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Временная метка, указывающая, когда был создан.', verbose_name='Создан')),
                ('user', models.ForeignKey(help_text='Пользователь, которому принадлежит вопрос.', on_delete=django.db.models.deletion.CASCADE, to='main.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Поддержка Telegram',
                'verbose_name_plural': 'Поддержка Telegram',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='Ответ на вопрос пользователя.', verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Временная метка, указывающая, когда был создан.', verbose_name='Создан')),
                ('admin_user', models.ForeignKey(help_text='Пользователь, которому выдана права администратора.', on_delete=django.db.models.deletion.CASCADE, to='main.telegramuser', verbose_name='Администратор')),
                ('questions', models.ForeignKey(help_text='Вопрос пользователя.', on_delete=django.db.models.deletion.CASCADE, to='main.telegramsupport', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответы на вопросы Telegram',
                'verbose_name_plural': 'Ответы на вопросы Telegram',
                'ordering': ['-created_at'],
            },
        ),
    ]
